# Generated by Django 5.0.4 on 2024-05-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_rename_genre_mangacard_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangacard',
            name='isbn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
