# Generated by Django 5.0.4 on 2024-05-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_mangacard_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangacard',
            name='isbn',
            field=models.CharField(max_length=255),
        ),
    ]
